export function getElements() {
  return {
    app: document.getElementById("app"),
    activityBar: document.getElementById("activityBar"),
    canvas: document.getElementById("canvasViewport"),
    world: document.getElementById("canvasWorld"),
    originCard: document.getElementById("originCard"),
    jsonComponentCard: document.getElementById("jsonComponentCard"),

    primarySidebar: document.getElementById("primarySidebar"),
    explorerView: document.getElementById("explorerView"),
    togglePrimarySidebarBtn: document.getElementById("togglePrimarySidebarBtn"),
    activityExplorerBtn: document.getElementById("activityExplorerBtn"),
    activitySearchBtn: document.getElementById("activitySearchBtn"),
    activityRunBtn: document.getElementById("activityRunBtn"),
    toggleSecondarySidebarBtn: document.getElementById("toggleSecondarySidebarBtn"),
    secondarySidebar: document.getElementById("secondarySidebar"),
    toggleBottomPanelBtn: document.getElementById("toggleBottomPanelBtn"),
    workbench: document.getElementById("workbench"),
    bottomPanel: document.getElementById("bottomPanel"),
    primarySidebarResizeHandle: document.getElementById("primarySidebarResizeHandle"),
    secondarySidebarResizeHandle: document.getElementById("secondarySidebarResizeHandle"),
    bottomPanelResizeHandle: document.getElementById("bottomPanelResizeHandle"),
    canvasMenuBtn: document.getElementById("canvasControlsTabBtn"),
    infiniteCanvasMenuBtn: document.getElementById("infiniteCanvasTabBtn"),
    componentsMenuBtn: document.getElementById("componentsTabBtn"),
    explorerSectionTabs: document.querySelector(".explorer-sections__tabs"),
    canvasControlsPanel: document.getElementById("canvasControlsPanel"),
    componentsPanel: document.getElementById("componentsPanel"),
    addJsonCardBtn: document.getElementById("addJsonCardBtn"),
    openJsonFileBtn: document.getElementById("openJsonFileBtn"),

    workspaceDisclosureBtn: document.getElementById("workspaceDisclosureBtn"),
    workspaceTree: document.getElementById("workspaceTree"),
    newFileBtn: document.getElementById("newFileBtn"),
    newFolderBtn: document.getElementById("newFolderBtn"),
    refreshExplorerBtn: document.getElementById("refreshExplorerBtn"),
    editorTabs: document.getElementById("editorTabs"),
    canvasTab: document.getElementById("canvasTab"),
    fileTabs: document.getElementById("fileTabs"),
    splitEditorBtn: document.getElementById("splitEditorBtn"),
    editorBreadcrumbKind: document.getElementById("editorBreadcrumbKind"),
    editorBreadcrumbName: document.getElementById("editorBreadcrumbName"),
    editorViewport: document.getElementById("editorViewport"),
    canvasView: document.getElementById("canvasView"),
    sourceEditorView: document.getElementById("sourceEditorView"),
    sourceScroller: document.getElementById("sourceScroller"),
    sourceContent: document.getElementById("sourceContent"),
    sourceMinimap: document.getElementById("sourceMinimap"),
    chatEmptyState: document.getElementById("chatEmptyState"),
    chatMessages: document.getElementById("chatMessages"),
    chatPromptInput: document.getElementById("chatPromptInput"),
    sendChatMessageBtn: document.getElementById("sendChatMessageBtn"),
    newChatBtn: document.getElementById("newChatBtn"),
    chatSettingsBtn: document.getElementById("chatSettingsBtn"),
    chatContextKind: document.getElementById("chatContextKind"),
    chatContextName: document.getElementById("chatContextName"),
    statusLanguage: document.getElementById("statusLanguage"),

    bottomPanelTabsRoot: document.getElementById("bottomPanelTabs"),
    bottomPanelTabs: [...document.querySelectorAll(".bottom-panel__tab[data-panel-view]")],
    bottomPanelViews: [...document.querySelectorAll(".bottom-panel__view")],
    problemsView: document.getElementById("problemsView"),
    outputView: document.getElementById("outputView"),
    debugConsoleView: document.getElementById("debugConsoleView"),
    terminalView: document.getElementById("terminalView"),
    newTerminalBtn: document.getElementById("newTerminalBtn"),
    splitTerminalBtn: document.getElementById("splitTerminalBtn"),
    killTerminalBtn: document.getElementById("killTerminalBtn"),
    maximizeBottomPanelBtn: document.getElementById("maximizeBottomPanelBtn"),
    closeBottomPanelBtn: document.getElementById("closeBottomPanelBtn"),
    maximizeSecondarySidebarBtn: document.getElementById("maximizeSecondarySidebarBtn"),
    closeSecondarySidebarBtn: document.getElementById("closeSecondarySidebarBtn"),

    grids: Object.fromEntries(
      [...document.querySelectorAll(".infinite-canvas__grid[data-grid-order]")]
        .map((layer) => [Number(layer.dataset.gridOrder), layer])
    ),

    zoomRange: document.getElementById("zoomRange"),
    zoomReadout: document.getElementById("zoomReadout"),
    lodBadge: document.getElementById("lodBadge"),
    zoomInBtn: document.getElementById("zoomInBtn"),
    zoomOutBtn: document.getElementById("zoomOutBtn"),

    setAnchorBtn: document.getElementById("setAnchorBtn"),
    goAnchorBtn: document.getElementById("goAnchorBtn"),
    clearAnchorBtn: document.getElementById("clearAnchorBtn"),
    anchorMarker: document.getElementById("anchorMarker"),

    homeBtn: document.getElementById("returnToOriginBtn"),
    canvasResetBtn: document.getElementById("resetCanvasBtn"),
    infiniteResetBtn: document.getElementById("resetWorkspaceBtn"),
    xStat: document.getElementById("xStat"),
    yStat: document.getElementById("yStat"),
    zoomStat: document.getElementById("zoomStat"),
    orderStat: document.getElementById("orderStat"),
    toast: document.getElementById("toastRegion"),
    lodRows: [...document.querySelectorAll(".lod-row")]
  };
}
