export function getElements() {
  return {
    app: document.getElementById("app"),
    canvas: document.getElementById("canvas"),
    world: document.getElementById("world"),
    originCard: document.getElementById("originCard"),
    jsonComponentCard: document.getElementById("jsonComponentCard"),

    sidebar: document.getElementById("sidebar"),
    primarySidebarLayoutBtn: document.getElementById("primarySidebarLayoutBtn"),
    explorerActivityBtn: document.getElementById("explorerActivityBtn"),
    secondarySidebarLayoutBtn: document.getElementById("secondarySidebarLayoutBtn"),
    chatPanel: document.getElementById("chatPanel"),
    panelLayoutBtn: document.getElementById("panelLayoutBtn"),
    workbench: document.getElementById("workbench"),
    terminalPanel: document.getElementById("terminalPanel"),
    primarySidebarResizeHandle: document.getElementById("primarySidebarResizeHandle"),
    secondarySidebarResizeHandle: document.getElementById("secondarySidebarResizeHandle"),
    terminalPanelResizeHandle: document.getElementById("terminalPanelResizeHandle"),
    canvasMenuBtn: document.getElementById("canvasMenuBtn"),
    infiniteCanvasMenuBtn: document.getElementById("infiniteCanvasMenuBtn"),
    componentsMenuBtn: document.getElementById("componentsMenuBtn"),
    canvasControlsPanel: document.getElementById("canvasControlsPanel"),
    componentsPanel: document.getElementById("componentsPanel"),
    addJsonCardBtn: document.getElementById("addJsonCardBtn"),
    openJsonFileBtn: document.getElementById("openJsonFileBtn"),

    workspaceFileTree: document.getElementById("workspaceFileTree"),
    workspaceCanvasTab: document.getElementById("workspaceCanvasTab"),
    workspaceCodeTab: document.getElementById("workspaceCodeTab"),
    workspaceCodeTabKind: document.getElementById("workspaceCodeTabKind"),
    workspaceCodeTabName: document.getElementById("workspaceCodeTabName"),
    workspaceBreadcrumbKind: document.getElementById("workspaceBreadcrumbKind"),
    workspaceBreadcrumbName: document.getElementById("workspaceBreadcrumbName"),
    canvasEditorView: document.getElementById("canvasEditorView"),
    codeEditorView: document.getElementById("codeEditorView"),
    sourceCode: document.getElementById("sourceCode"),
    sourceMinimap: document.getElementById("sourceMinimap"),
    chatContextKind: document.getElementById("chatContextKind"),
    chatContextName: document.getElementById("chatContextName"),
    statusLanguage: document.getElementById("statusLanguage"),

    grids: {
      1: document.getElementById("grid1"),
      2: document.getElementById("grid2"),
      4: document.getElementById("grid4"),
      8: document.getElementById("grid8")
    },

    zoomRange: document.getElementById("zoomRange"),
    zoomReadout: document.getElementById("zoomReadout"),
    lodBadge: document.getElementById("lodBadge"),
    zoomInBtn: document.getElementById("zoomInBtn"),
    zoomOutBtn: document.getElementById("zoomOutBtn"),

    setAnchorBtn: document.getElementById("setAnchorBtn"),
    goAnchorBtn: document.getElementById("goAnchorBtn"),
    clearAnchorBtn: document.getElementById("clearAnchorBtn"),
    anchorMarker: document.getElementById("anchorMarker"),

    homeBtn: document.getElementById("homeBtn"),
    canvasResetBtn: document.getElementById("canvasResetBtn"),
    infiniteResetBtn: document.getElementById("infiniteResetBtn"),
    xStat: document.getElementById("xStat"),
    yStat: document.getElementById("yStat"),
    zoomStat: document.getElementById("zoomStat"),
    orderStat: document.getElementById("orderStat"),
    toast: document.getElementById("toast"),
    lodRows: [...document.querySelectorAll(".lod-row")]
  };
}
