import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entryFile = resolve(repositoryRoot, "css/creed-main.css");
const outputFile = resolve(repositoryRoot, "css/generated/creed.css");
const importPattern = /^\s*@import\s+url\(["'](.+?)["']\);\s*$/gm;
const checkOnly = process.argv.includes("--check");

function expandImports(filePath, stack = []) {
  if (stack.includes(filePath)) {
    throw new Error("Circular CSS import: " + [...stack, filePath].join(" -> "));
  }

  const source = readFileSync(filePath, "utf8");
  const nextStack = [...stack, filePath];
  let output = "";
  let cursor = 0;

  for (const match of source.matchAll(importPattern)) {
    output += source.slice(cursor, match.index);
    const importedFile = resolve(dirname(filePath), match[1]);
    output += "\n/* source: " + importedFile.slice(repositoryRoot.length + 1) + " */\n";
    output += expandImports(importedFile, nextStack);
    cursor = match.index + match[0].length;
  }

  return output + source.slice(cursor);
}

const banner = "/* Generated by scripts/build-css.mjs. Edit css source colonies, not this file. */\n";
const nextOutput = banner + expandImports(entryFile).trim() + "\n";

if (checkOnly) {
  const currentOutput = readFileSync(outputFile, "utf8");
  if (currentOutput !== nextOutput) {
    console.error("Generated CSS is stale. Run: npm run build:css");
    process.exit(1);
  }
  console.log("Generated CSS bundle is synchronized.");
} else {
  writeFileSync(outputFile, nextOutput);
}
